// Two robbers online: A makes a public lobby, B joins by code, they chat, walk around the Hideout, A picks the plan and
// starts; both land at the bank with 2 CPUs; B masks up and shoots; B leaves and a CPU takes over.
import WebSocket from 'ws';
const url = process.env.URL || 'ws://localhost:8131';
const mk = name => new Promise(res => { const ws = new WebSocket(url); ws.log = []; ws.on('message', r => { const m = JSON.parse(r); ws.log.push(m); if (m.t === 'hello') { ws.id = m.id; ws.send(JSON.stringify({ t: 'me', name, color: '#26262a', skin: 'none', mask: 'clown' })); res(ws); } }); });
const wait = (ws, f, ms = 8000) => new Promise((res, rej) => { const t0 = Date.now(); const iv = setInterval(() => { const m = ws.log.find(f); if (m) { clearInterval(iv); res(m); } else if (Date.now() - t0 > ms) { clearInterval(iv); rej(new Error('timeout waiting')); } }, 20); });
const tx = (ws, m) => ws.send(JSON.stringify(m));
const A = await mk('ALICE'), B = await mk('BOB');
tx(A, { t: 'create', public: true });
const code = (await wait(A, m => m.t === 'joined')).code;
tx(B, { t: 'list' }); const list = await wait(B, m => m.t === 'list');
console.log('public list shows', list.rooms.map(r => r.code + ' ' + r.name).join(', '));
tx(B, { t: 'join', code });
const wb = await wait(B, m => m.t === 'world');
console.log('B joined', code, 'map', wb.map, '(1 = Hideout) crew', wb.players.map(p => p.name + (p.bot ? '(cpu)' : '')).join(' '));
tx(B, { t: 'chat', text: 'hi alice!' });
console.log('chat reached A:', (await wait(A, m => m.t === 'chat' && m.text === 'hi alice!')).from);
tx(B, { t: 'st', x: 3, y: 0, z: 1, yaw: 0, g: 1 });
await new Promise(r => setTimeout(r, 300));
const snap = [...A.log].reverse().find(m => m.t === 'snap');
console.log('A sees B walking in the Hideout', snap.e.find(e => e[0] === B.id).slice(1, 4));
tx(A, { t: 'set', settings: { plan: 'loud', diff: 0 } });
tx(A, { t: 'start' });
const wa2 = await wait(A, m => m.t === 'world' && m.map === 0), wb2 = await wait(B, m => m.t === 'world' && m.map === 0);
console.log('heist started for both at the bank; crew', wa2.players.map(p => `${p.name}${p.bot ? '(cpu)' : ''}`).join(' '), '· npcs', wa2.npcs.length, '· plan', wa2.settings.plan);
tx(B, { t: 'mask' });
console.log('B masked:', (await wait(A, m => m.t === 'fx' && m.k === 'mask' && m.id === B.id)).k);
const me = wb2.players.find(p => p.id === B.id);
tx(B, { t: 'shoot', o: [me.x, 1.3, me.z], d: [0, 0, -1] });
const shot = await wait(A, m => m.t === 'shot' && m.id === B.id);
console.log('A saw B shoot; hit', shot.h, 'wall', shot.wall);
await new Promise(r => setTimeout(r, 1500));
const bm = [...B.log].reverse().find(m => m.t === 'me');
console.log('B me:', { mag: bm.mag, masked: bm.masked, hp: bm.hp });
B.close();
await wait(A, m => m.t === 'gone' && m.id === B.id);
const cpu = await wait(A, m => m.t === 'join' && m.p.bot && m.p.masked);
console.log('B left; CPU', cpu.p.name, 'took over');
process.exit(0);
